-- AI Opportunity Scout — Seed Data
-- Sample events for testing and development

-- Insert sample events
INSERT INTO events (id, title, description, short_summary, platform, event_type, tags, domains, programming_languages, prize, prize_amount, location, is_remote, is_free, eligibility, organizer, registration_url, image_url, source_url, ai_score, popularity_score, external_id, is_active, is_verified, participant_count, extra_data, created_at, updated_at, crawled_at)
VALUES
  (gen_random_uuid(), 'Smart India Hackathon 2025', 'A nationwide hackathon where students solve real problems of India''s ministries and departments.', 'India''s largest hackathon. Solve real government problems and win ₹1 Lakh+.', 'unstop', 'hackathon', ARRAY['india','hackathon','government'], ARRAY['Software Engineering','AI/ML'], ARRAY[]::VARCHAR[], '₹1,00,000', 1200.0, 'Delhi, India', false, true, 'Indian college students', 'AICTE', 'https://www.sih.gov.in/', NULL, NULL, 87.0, 95.0, NULL, true, true, 5000, '{}'::JSONB, NOW(), NOW(), NOW()),
  (gen_random_uuid(), 'Google Summer of Code 2025', 'GSoC is a global program focused on bringing more student developers into open source development.', 'Earn $1,500-$6,600 by contributing to top open source organizations with Google mentorship.', 'gsoc', 'open_source', ARRAY['gsoc','google','open source','summer'], ARRAY['Open Source','Software Engineering'], ARRAY[]::VARCHAR[], '$1,500 - $6,600', 6600.0, 'Remote', true, true, 'Students & beginners', 'Google', 'https://summerofcode.withgoogle.com/', NULL, NULL, 95.0, 99.0, NULL, true, true, 2000, '{}'::JSONB, NOW(), NOW(), NOW()),
  (gen_random_uuid(), 'Codeforces Round #876 Div. 2', 'A competitive programming contest on Codeforces for Div. 2 participants.', 'Codeforces round for intermediate competitive programmers. Great for practice and rating.', 'codeforces', 'contest', ARRAY['competitive programming','algorithms'], ARRAY['Computer Science'], ARRAY[]::VARCHAR[], NULL, 0.0, 'Online', true, true, 'All registered users', 'Codeforces', 'https://codeforces.com/contests', NULL, NULL, 72.0, 80.0, NULL, true, true, 15000, '{}'::JSONB, NOW(), NOW(), NOW()),
  (gen_random_uuid(), 'Microsoft Imagine Cup 2025', 'The Imagine Cup is an annual competition by Microsoft for students worldwide to build innovative tech solutions.', 'Win $100K and a mentoring session with Microsoft CEO. Build AI, cloud, or mixed reality solutions.', 'microsoft', 'competition', ARRAY['microsoft','competition','ai','azure'], ARRAY['AI/ML','Cloud'], ARRAY[]::VARCHAR[], '$100,000', 100000.0, 'Global / Online', true, true, 'Students age 16+', 'Microsoft', 'https://imaginecup.microsoft.com/', NULL, NULL, 90.0, 92.0, NULL, true, true, 10000, '{}'::JSONB, NOW(), NOW(), NOW()),
  (gen_random_uuid(), 'MLH Global Hack Week: AI', 'A week-long hackathon series focused on AI/ML projects for student developers.', 'Build AI projects with MLH in a week-long virtual hackathon with workshops and prizes.', 'mlh', 'hackathon', ARRAY['mlh','ai','machine learning'], ARRAY['AI/ML'], ARRAY[]::VARCHAR[], 'Swag & Recognition', 200.0, 'Online', true, true, 'Anyone / Students', 'Major League Hacking', 'https://mlh.io/', NULL, NULL, 75.0, 85.0, NULL, true, true, 3000, '{}'::JSONB, NOW(), NOW(), NOW()),
  (gen_random_uuid(), 'Kaggle ML Competition: House Prices', 'Predict house prices using advanced regression techniques. Great for beginners to practice ML.', 'A beginner-friendly Kaggle competition to practice regression modeling and data science.', 'kaggle', 'competition', ARRAY['kaggle','machine learning','regression'], ARRAY['Data Science','AI/ML'], ARRAY[]::VARCHAR[], 'Knowledge', 0.0, 'Online', true, true, 'All registered users', 'Kaggle', 'https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques', NULL, NULL, 68.0, 75.0, NULL, true, true, 8000, '{}'::JSONB, NOW(), NOW(), NOW()),
  (gen_random_uuid(), 'HackerEarth June Sprint', 'A 2-week coding sprint on HackerEarth testing DSA and problem-solving.', 'Monthly sprint to sharpen algorithms and data structures skills with cash prizes.', 'hackerearth', 'contest', ARRAY['hackerearth','sprint','dsa'], ARRAY['Computer Science'], ARRAY[]::VARCHAR[], '₹50,000', 600.0, 'Online', true, true, 'All developers', 'HackerEarth', 'https://hackerearth.com/', NULL, NULL, 65.0, 70.0, NULL, true, true, 4000, '{}'::JSONB, NOW(), NOW(), NOW()),
  (gen_random_uuid(), 'GirlScript Summer of Code 2025', 'GSSoC is a 3-month open-source program by GirlScript Foundation for students.', 'Contribute to open-source for 3 months, earn swag, recognition, and build your portfolio.', 'gssoc', 'open_source', ARRAY['gssoc','open source','student','india'], ARRAY['Open Source'], ARRAY[]::VARCHAR[], 'Swag + Certificates', 100.0, 'Remote', true, true, 'All students', 'GirlScript Foundation', 'https://gssoc.girlscript.tech/', NULL, NULL, 72.0, 80.0, NULL, true, true, 5000, '{}'::JSONB, NOW(), NOW(), NOW()),
  (gen_random_uuid(), 'Devfolio ETHIndia 2025', 'ETHIndia is Asia''s largest Ethereum hackathon, bringing together the brightest minds in web3.', 'Build on Ethereum and win crypto prizes at India''s largest web3 hackathon.', 'devfolio', 'hackathon', ARRAY['ethereum','web3','blockchain','crypto'], ARRAY['Blockchain','Web3'], ARRAY[]::VARCHAR[], '$1,00,000+', 100000.0, 'Bengaluru, India', false, true, 'Developers worldwide', 'Devfolio', 'https://ethindia.co/', NULL, NULL, 82.0, 94.0, NULL, true, true, 2000, '{}'::JSONB, NOW(), NOW(), NOW()),
  (gen_random_uuid(), 'Google STEP Internship 2025', 'The Student Training in Engineering Program (STEP) is an internship for 1st and 2nd year students.', 'Paid internship at Google for underrepresented CS students. Great mentorship and stipend.', 'google', 'internship', ARRAY['google','internship','paid','student'], ARRAY['Software Engineering'], ARRAY[]::VARCHAR[], 'Paid ($6,900+/month)', 6900.0, 'Google Offices', true, true, '1st/2nd year CS students', 'Google', 'https://buildyourfuture.withgoogle.com/programs/step', NULL, NULL, 93.0, 98.0, NULL, true, true, 1000, '{}'::JSONB, NOW(), NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Insert admin user (password: admin123)
-- MD5/bcrypt hashed 'admin123'
INSERT INTO users (id, email, username, full_name, hashed_password, is_admin, is_verified, is_active, created_at, updated_at)
VALUES (gen_random_uuid(), 'admin@aiopportunityscout.com', 'admin', 'Admin User', '$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW', true, true, true, NOW(), NOW())
ON CONFLICT (email) DO NOTHING;

-- Insert demo user (password: demo123)
-- MD5/bcrypt hashed 'demo123'
INSERT INTO users (id, email, username, full_name, hashed_password, is_admin, is_verified, is_active, created_at, updated_at)
VALUES (gen_random_uuid(), 'demo@example.com', 'demouser', 'Demo Student', '$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW', false, true, true, NOW(), NOW())
ON CONFLICT (email) DO NOTHING;
