"""add_composite_indexes_and_security

Revision ID: b28114e9851c
Revises: 00bb5e3e8ff4
Create Date: 2026-07-20 01:14:36.447378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b28114e9851c'
down_revision: Union[str, None] = '00bb5e3e8ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_events_active_deadline', 'events', ['is_active', 'registration_deadline'], unique=False)
    op.create_index('ix_events_content_hash_unique', 'events', ['content_hash'], unique=True)
    op.create_index('ix_events_platform_active_score', 'events', ['platform', 'is_active', 'ai_score'], unique=False)
    op.create_index('ix_events_type_active', 'events', ['event_type', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_type_active', table_name='events')
    op.drop_index('ix_events_platform_active_score', table_name='events')
    op.drop_index('ix_events_content_hash_unique', table_name='events')
    op.drop_index('ix_events_active_deadline', table_name='events')
    # ### end Alembic commands ###
