"""update_scheduler_log_fields

Revision ID: ccd2cda84651
Revises: b28114e9851c
Create Date: 2026-07-20 01:27:46.734662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccd2cda84651'
down_revision: Union[str, None] = 'b28114e9851c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler_logs', sa.Column('job_id', sa.String(length=100), nullable=True))
    op.add_column('scheduler_logs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('scheduler_logs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scheduler_logs', sa.Column('platforms_crawled', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('scheduler_logs', sa.Column('events_found', sa.Integer(), nullable=True))
    op.add_column('scheduler_logs', sa.Column('events_new', sa.Integer(), nullable=True))
    op.add_column('scheduler_logs', sa.Column('emails_sent', sa.Integer(), nullable=True))
    op.add_column('scheduler_logs', sa.Column('telegrams_sent', sa.Integer(), nullable=True))
    op.add_column('scheduler_logs', sa.Column('failures', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('scheduler_logs', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('scheduler_logs', sa.Column('trigger_source', sa.String(length=50), nullable=True))
    op.drop_column('scheduler_logs', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler_logs', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('scheduler_logs', 'trigger_source')
    op.drop_column('scheduler_logs', 'retry_count')
    op.drop_column('scheduler_logs', 'failures')
    op.drop_column('scheduler_logs', 'telegrams_sent')
    op.drop_column('scheduler_logs', 'emails_sent')
    op.drop_column('scheduler_logs', 'events_new')
    op.drop_column('scheduler_logs', 'events_found')
    op.drop_column('scheduler_logs', 'platforms_crawled')
    op.drop_column('scheduler_logs', 'completed_at')
    op.drop_column('scheduler_logs', 'started_at')
    op.drop_column('scheduler_logs', 'job_id')
    # ### end Alembic commands ###
